import type { ArchitectureCaseStudy } from '@/types/architecture'

export const architectureTheme = {
  colors: {
    background: '#0B1020',
    card: '#111827',
    primary: '#22D3EE',
    secondary: '#8B5CF6',
    accent: '#F59E0B',
    success: '#10B981',
    database: '#64748B',
    text: '#E2E8F0',
    muted: '#94A3B8',
  },
}

const notificationStudy: ArchitectureCaseStudy = {
  slug: 'push-notification-system',
  title: 'Push Notification Architecture',
  summary:
    'An event-driven notification platform that supports real-time, scheduled, and preference-aware delivery while keeping the user request path fast.',
  chips: ['Kafka', 'GraphQL', 'NestJS', 'MongoDB'],
  outcome: 'Lower latency, higher delivery resilience, and a full audit trail for every notification event.',
  stack: ['React Native', 'NestJS', 'Kafka', 'Node.js', 'MongoDB', 'Expo'],
  metrics: [
    { label: 'Async Backbone', value: 'Kafka', detail: 'Decouples user actions from delivery' },
    { label: 'Delivery', value: 'Expo', detail: 'Push request to device at scale' },
    { label: 'History', value: 'MongoDB', detail: 'Stores audit and retry records' },
    { label: 'Reliability', value: 'Retries', detail: 'Handles transient failures safely' },
  ],
  overview: [
    'React Native triggers a GraphQL mutation.',
    'NestJS gateway validates and publishes a notification event.',
    'Kafka carries the event to a dedicated worker service.',
    'Notification records are persisted before delivery and lifecycle state is tracked.',
  ],
  challenges: [
    'Preventing blocking behavior in the request path.',
    'Handling third-party push failures and retries.',
    'Maintaining delivery history across consumer restarts.',
    'Validating user preferences and device token freshness before send.',
  ],
  scaling: [
    'Scale gateway and workers independently.',
    'Use Kafka partitions to spread consumer load.',
    'Add dead-letter handling for failed deliveries.',
    'Support scheduler-based campaigns through a separate trigger path.',
  ],
  lessons: [
    'Asynchronous delivery protects the user experience.',
    'Event history is essential for debugging and auditability.',
    'Idempotency matters whenever retries are introduced.',
    'Device lifecycle and preference validation must happen before every send.',
  ],
  nodes: [
    {
      id: 'client',
      label: 'React Native App',
      subtitle: 'Client Layer',
      layer: 'client',
      x: 60,
      y: 260,
      details: ['User action starts the notification workflow.', 'Submits GraphQL mutations from mobile.'],
    },
    {
      id: 'gateway',
      label: 'GraphQL Gateway',
      subtitle: 'API Layer',
      layer: 'api',
      x: 420,
      y: 260,
      details: ['Validates request payloads.', 'Publishes domain events to Kafka.'],
    },
    {
      id: 'kafka',
      label: 'Kafka Topic',
      subtitle: 'Event Layer',
      layer: 'event',
      x: 860,
      y: 260,
      details: ['Buffers traffic bursts.', 'Provides durable async handoff.'],
    },
    {
      id: 'worker',
      label: 'Notification Service',
      subtitle: 'Microservices',
      layer: 'service',
      x: 1240,
      y: 200,
      details: ['Consumes events.', 'Persists history.', 'Calls Expo for delivery.'],
    },
    {
      id: 'mongo',
      label: 'MongoDB',
      subtitle: 'Data Layer',
      layer: 'database',
      x: 1240,
      y: 560,
      details: ['Notification records and status history.', 'Audit trail for support and analytics.'],
    },
    {
      id: 'expo',
      label: 'Expo Push Service',
      subtitle: 'External Services',
      layer: 'external',
      x: 1660,
      y: 200,
      details: ['Device push delivery API.', 'Abstracts iOS and Android push mechanics.'],
    },
    {
      id: 'device',
      label: 'Mobile Device',
      subtitle: 'External Services',
      layer: 'external',
      x: 1660,
      y: 560,
      details: ['Receives the final push notification.'],
    },
    {
      id: 'obs',
      label: 'Observability',
      subtitle: 'Monitoring',
      layer: 'monitoring',
      x: 60,
      y: 760,
      details: ['Logs, traces, lag, and retry metrics.'],
    },
    {
      id: 'scheduler',
      label: 'Scheduler / Cron',
      subtitle: 'Trigger Layer',
      layer: 'api',
      x: 420,
      y: 520,
      details: ['Schedules campaigns and delayed notifications.', 'Publishes time-based notification jobs.'],
    },
    {
      id: 'prefs',
      label: 'Preference Service',
      subtitle: 'Policy Layer',
      layer: 'service',
      x: 860,
      y: 560,
      details: ['Validates mute rules and channel preferences.', 'Blocks sends that violate user settings.'],
    },
    {
      id: 'devices',
      label: 'Device Registry',
      subtitle: 'Lifecycle Data',
      layer: 'database',
      x: 1240,
      y: 760,
      details: ['Stores active tokens and platform metadata.', 'Tracks token rotation and invalidation.'],
    },
    {
      id: 'dlq',
      label: 'Dead-Letter Queue',
      subtitle: 'Retry Safety Net',
      layer: 'event',
      x: 1660,
      y: 760,
      details: ['Captures poison messages.', 'Enables replay and manual triage.'],
    },
  ],
  edges: [
    { id: 'e1', source: 'client', target: 'gateway', label: 'GraphQL Mutation', style: 'primary' },
    { id: 'e2', source: 'gateway', target: 'kafka', label: 'Publish Event', style: 'event' },
    { id: 'e3', source: 'kafka', target: 'worker', label: 'Consume Event', style: 'event' },
    { id: 'e4', source: 'scheduler', target: 'gateway', label: 'Schedule Trigger', style: 'primary' },
    { id: 'e5', source: 'worker', target: 'prefs', label: 'Validate Preferences', style: 'primary' },
    { id: 'e6', source: 'prefs', target: 'devices', label: 'Resolve Active Tokens', style: 'bidirectional' },
    { id: 'e7', source: 'worker', target: 'mongo', label: 'Persist Notification', style: 'primary' },
    { id: 'e8', source: 'worker', target: 'expo', label: 'Send Push', style: 'primary' },
    { id: 'e9', source: 'expo', target: 'device', label: 'Push Delivery', style: 'primary' },
    { id: 'e10', source: 'worker', target: 'mongo', label: 'Update Status', style: 'bidirectional' },
    { id: 'e11', source: 'worker', target: 'dlq', label: 'Retry Exhausted', style: 'retry' },
    { id: 'e12', source: 'worker', target: 'obs', label: 'Logging', style: 'observability' },
    { id: 'e13', source: 'gateway', target: 'obs', label: 'Metrics', style: 'observability' },
    { id: 'e14', source: 'worker', target: 'gateway', label: 'Retry Event', style: 'retry' },
  ],
}

export const architectureCaseStudies = [notificationStudy]
