-- This migration is intentionally left as a no-op.
-- ResumeAsset already exists in the initial migration, and the duplicate
-- table creation caused shadow database failures during later migrations.
